"""Run all analyses and render data-backed docs, notebook artifacts, and extracts."""
from __future__ import annotations
import json
from pathlib import Path
import sys

import nbformat as nbf
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.gmv_analysis import (monthly_gmv_decomposition, seller_health, price_elasticity,
                              slowdown_diagnosis, churn_gmv_relationship)
from src.search_analysis import search_funnel, zero_result_trend, rank_ctr, cliff_point, cohort_retention
from src.ab_test_cuped import required_sample_size, simulate_experiment


def load() -> dict[str, pd.DataFrame]:
    return {n: pd.read_parquet(ROOT / "data" / f"{n}.parquet") for n in ["sellers", "listings", "search_events", "transactions"]}


def money(x: float) -> str:
    return f"${abs(x):,.0f}" if x >= 0 else f"-${abs(x):,.0f}"


def notebook(title: str, intro: str, cells: list[str], path: Path) -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = [nbf.v4.new_markdown_cell(f"# {title}\n\n{intro}")] + [nbf.v4.new_code_cell(c) for c in cells]
    nb.metadata.kernelspec = {"display_name": "Python 3", "language": "python", "name": "python3"}
    nbf.write(nb, path)


def main() -> None:
    d = load()
    decomp = monthly_gmv_decomposition(d["transactions"])
    health = seller_health(d["sellers"], d["listings"], d["transactions"])
    elasticity = price_elasticity(d["transactions"])
    diagnosis = slowdown_diagnosis(decomp)
    relationship = churn_gmv_relationship(d["sellers"], d["transactions"])
    funnel = search_funnel(d["search_events"], d["transactions"])
    zero = zero_result_trend(d["search_events"])
    ctr = rank_ctr(d["search_events"])
    cliff = cliff_point(d["search_events"])
    retention = cohort_retention(d["transactions"])
    experiment = simulate_experiment()
    required_n = required_sample_size(.08, .05)

    derived = ROOT / "data" / "derived"
    derived.mkdir(exist_ok=True)
    for name, frame in {"gmv_decomposition": decomp, "seller_health": health,
                        "price_elasticity": elasticity, "search_funnel": funnel,
                        "zero_result_trend": zero, "rank_ctr": ctr}.items():
        frame.to_parquet(derived / f"{name}.parquet", index=False)
    retention.to_csv(derived / "cohort_retention.csv")

    segments = health.health_segment.value_counts()
    latest_cat = decomp[decomp.month == decomp.month.max()].sort_values("gmv")
    worst_cat = latest_cat.iloc[0].category
    top_ctr = funnel[funnel.rank_bucket == "1-5"].clicks.sum() / len(d["search_events"])
    below_ctr = funnel[funnel.rank_bucket.isin(["11-20", "21-50"])].clicks.sum() / len(d["search_events"])
    projected_ctr_lift = (top_ctr - below_ctr) * .08
    projected_gmv = diagnosis["latest_gmv"] * projected_ctr_lift
    dominant = max([("buyer growth", diagnosis["buyer_impact"]), ("purchase frequency", diagnosis["frequency_impact"]), ("pricing/AOV", diagnosis["aov_impact"])], key=lambda x: abs(x[1]))

    exec_memo = f"""# Executive memo: Marketplace GMV diagnosis

**To:** VP, Marketplace  
**Period:** 12 months ending {diagnosis['latest_month']}  
**Decision:** Prioritize seller supply and discovery in the weak-search categories; do not use broad discounting as the first response.

## What changed

GMV moved **{diagnosis['gmv_change_pct']:.1%}** over the latest three-month window, a **{money(diagnosis['gmv_change'])}** change from a {money(diagnosis['prior_gmv'])} baseline. The largest mechanical component was **{dominant[0]}** ({money(dominant[1])}); buyer contribution was {money(diagnosis['buyer_impact'])}, order-frequency contribution was {money(diagnosis['frequency_impact'])}, and AOV contribution was {money(diagnosis['aov_impact'])}. **{worst_cat}** had the lowest latest-month category GMV.

## Why it happened

Low-fulfillment sellers churned at **{d['sellers'].query('fulfillment_rate < .90').is_churned.mean():.1%}**, versus **{d['sellers'].query('fulfillment_rate >= .90').is_churned.mean():.1%}** for other sellers. Across categories, seller churn and three-month GMV change had correlation **{relationship['correlation']:.2f}** (OLS coefficient {relationship['coefficient']:.2f}, p={relationship['p_value']:.3f}). This is observational evidence of association, not proof of causality; the proposed ranking experiment provides the causal test.

## Action and value

Boost under-exposed listings from sellers with fulfillment ≥90%, monitor supply retention, and focus the launch on Electronics and Fashion. Redirecting 8% of below-fold exposure toward top-rank-like relevance implies an estimated **{projected_ctr_lift:.2%} CTR lift** and approximately **{money(projected_gmv)} monthly GMV opportunity**, before incrementality and capacity discounts. Use the experiment plan to validate this estimate.

_Generated by `data/build_artifacts.py` from the current parquet tables._
"""
    (ROOT / "docs" / "exec_memo.md").write_text(exec_memo, encoding="utf-8")

    prd = f"""# Product PRD: Fulfillment-aware discovery ranking

## Problem

Search CTR is **{top_ctr:.2%}** at ranks 1–5 but only **{below_ctr:.2%}** below rank 10. The detected curve cliff is near rank **{cliff}**. Zero-result rates peak in categories where discovery quality and late-period GMV are weakest.

## Proposal

Add a bounded fulfillment-quality boost to the relevance score for active listings whose sellers have fulfillment ≥90%, strong ratings, and low historic exposure. Preserve query relevance as the primary score and cap the boost so poor matches cannot leapfrog relevant inventory.

## Success metrics

- Primary: purchase-through rate per search; target relative lift 5%.
- Secondary: CTR, zero-result rate, GMV per search, and exposure share for qualified sellers.
- Guardrails: refunds, p95 page latency, seller complaints, and category concentration.

## Expected value and rollout

Moving 8% of buried impressions toward top-rank performance produces a directional **{projected_ctr_lift:.2%} absolute CTR lift** and **{money(projected_gmv)} monthly GMV opportunity**. Validate at 5% traffic, then 25%, before full rollout. Required sample size is approximately **{required_n:,} users per arm** for 80% power at α=.05, an 8% baseline purchase rate, and 5% relative lift.

_Generated by `data/build_artifacts.py` from the current parquet tables._
"""
    (ROOT / "docs" / "product_prd.md").write_text(prd, encoding="utf-8")

    n, c = experiment["naive"], experiment["cuped"]
    guards = experiment["guardrails"]
    ship = c.p_value < .05 and c.effect > 0 and abs(guards["refund_rate_delta"]) < .002 and guards["page_load_ms_delta"] < 10
    readout = f"""# Experiment readout: Fulfillment-aware ranking

## Recommendation: {'SHIP via staged rollout' if ship else 'DO NOT SHIP YET'}

The simulated test included 40,000 buyers. CUPED used historical buyer purchase propensity as a pre-period covariate and reduced outcome variance by **{experiment['variance_reduction']:.1%}**.

| Method | Absolute lift | 95% CI | p-value |
|---|---:|---:|---:|
| Naive two-proportion | {n.effect:.3%} | [{n.ci_low:.3%}, {n.ci_high:.3%}] | {n.p_value:.4f} |
| CUPED-adjusted | {c.effect:.3%} | [{c.ci_low:.3%}, {c.ci_high:.3%}] | {c.p_value:.4f} |

## Guardrails

- Refund-rate delta: {guards['refund_rate_delta']:.3%}
- Page-load delta: {guards['page_load_ms_delta']:.1f} ms
- Seller-complaint-rate delta: {guards['seller_complaint_rate_delta']:.3%}

## Rollout

1. **5% for 7 days:** validate instrumentation, novelty, latency, and complaint routing.
2. **25% for 14 days:** confirm category-level lift and seller exposure distribution.
3. **100%:** ship only if the CUPED CI remains positive and no guardrail breaches; retain a 5% holdout for four weeks.

_Generated by `data/build_artifacts.py`; outcomes are simulated and reproducible with seed 42._
"""
    (ROOT / "docs" / "experiment_readout.md").write_text(readout, encoding="utf-8")

    notebook("Business diagnosis", "GMV decomposition, seller health, elasticity, and churn association.", [
        "from pathlib import Path\nimport sys, pandas as pd\nROOT=Path.cwd().parent if Path.cwd().name=='notebooks' else Path.cwd()\nsys.path.insert(0,str(ROOT))",
        "from src.gmv_analysis import *\ntx=pd.read_parquet(ROOT/'data/transactions.parquet'); sellers=pd.read_parquet(ROOT/'data/sellers.parquet'); listings=pd.read_parquet(ROOT/'data/listings.parquet')",
        "monthly_gmv_decomposition(tx).tail(12)", "seller_health(sellers,listings,tx).health_segment.value_counts()", "price_elasticity(tx)"], ROOT / "notebooks/01_business_diagnosis.ipynb")
    notebook("Product investigation", "Search funnel, rank cliff, zero results, and buyer retention.", [
        "from pathlib import Path\nimport sys, pandas as pd\nROOT=Path.cwd().parent if Path.cwd().name=='notebooks' else Path.cwd()\nsys.path.insert(0,str(ROOT))",
        "from src.search_analysis import *\ns=pd.read_parquet(ROOT/'data/search_events.parquet'); tx=pd.read_parquet(ROOT/'data/transactions.parquet')",
        "search_funnel(s,tx)", "zero_result_trend(s).tail(12)", "rank_ctr(s).head(15)", "cohort_retention(tx)"], ROOT / "notebooks/02_product_investigation.ipynb")
    notebook("A/B test validation with CUPED", "Power, naive testing, CUPED variance reduction, and guardrails.", [
        "from pathlib import Path\nimport sys\nROOT=Path.cwd().parent if Path.cwd().name=='notebooks' else Path.cwd()\nsys.path.insert(0,str(ROOT))",
        "from src.ab_test_cuped import *", "required_sample_size(.08,.05)", "r=simulate_experiment(); r['naive'], r['cuped'], r['variance_reduction'], r['guardrails']"], ROOT / "notebooks/03_ab_test_validation.ipynb")

    summary = {"diagnosis": diagnosis, "relationship": relationship, "cliff_rank": cliff,
               "top5_ctr": top_ctr, "below10_ctr": below_ctr, "projected_ctr_lift": projected_ctr_lift,
               "projected_monthly_gmv": projected_gmv, "variance_reduction": experiment["variance_reduction"],
               "naive_p": n.p_value, "cuped_p": c.p_value, "health_segments": segments.to_dict()}
    (derived / "summary.json").write_text(json.dumps(summary, indent=2, default=float), encoding="utf-8")
    readme = f"""# Marketplace Growth & Pricing Intelligence Platform

[![Python](https://img.shields.io/badge/Python-3.11+-3776AB?logo=python&logoColor=white)](https://python.org) [![Streamlit](https://img.shields.io/badge/Streamlit-dashboard-FF4B4B?logo=streamlit&logoColor=white)](https://streamlit.io) [![DuckDB](https://img.shields.io/badge/DuckDB-SQL-FFF000?logo=duckdb&logoColor=black)](https://duckdb.org) [![Plotly](https://img.shields.io/badge/Plotly-interactive-3F4F75?logo=plotly&logoColor=white)](https://plotly.com)

An end-to-end analytics portfolio project that diagnoses a two-sided marketplace GMV slowdown, traces it to seller supply and search discovery, proposes a fulfillment-aware ranking intervention, and validates that intervention using a reusable CUPED implementation. The repository combines 320K related search events, 41K transactions, production-style SQL, statistical analysis, decision documents, and a three-tab Streamlit dashboard.

> **Live app:** `https://YOUR-APP.streamlit.app` (replace after deployment)

## Architecture

```mermaid
flowchart LR
  G[Deterministic generator] --> D[(CSV + Parquet)]
  D --> SQL[DuckDB SQL]
  D --> PY[Reusable Python modules]
  PY --> N[Analysis notebooks]
  PY --> A[Streamlit app]
  PY --> DOC[Dynamic decision docs]
  E[A/B simulation] --> C[CUPED adjustment]
  C --> A
  C --> DOC
```

## Key findings

- Monthly GMV fell **{diagnosis['gmv_change_pct']:.1%}** over the final three-month window, a **{money(diagnosis['gmv_change'])}** change; buyer-count mechanics contributed {money(diagnosis['buyer_impact'])}.
- Search has a clear rank cliff at **position {cliff}**: ranks 1–5 contribute **{top_ctr:.2%} CTR**, while ranks below 10 contribute only **{below_ctr:.2%}**.
- Sellers below 90% fulfillment churn at **{d['sellers'].query('fulfillment_rate < .90').is_churned.mean():.1%}**, versus **{d['sellers'].query('fulfillment_rate >= .90').is_churned.mean():.1%}** above the threshold.
- The default experiment's historical covariate reduces outcome variance by **{experiment['variance_reduction']:.1%}**; its CUPED p-value is **{c.p_value:.4f}** versus **{n.p_value:.4f}** naively.

> **CUPED in one minute**  
> CUPED subtracts the portion of an experiment outcome predicted by a pre-experiment covariate. Here, historical buyer purchase propensity explains some otherwise noisy conversion variation. The adjusted metric keeps the treatment effect unbiased under randomization while reducing variance, which can tighten confidence intervals and increase effective power without adding traffic. The implementation in `src/ab_test_cuped.py` computes θ = Cov(Y, X) / Var(X) from scratch.

## Repository map

- `src/`: reusable generation, marketplace, search, and experiment functions
- `sql/`: GMV decomposition, search funnel, and seller-health queries
- `notebooks/`: business, product, and experimentation walkthroughs
- `docs/`: dynamically generated executive memo, PRD, and experiment readout
- `app/streamlit_app.py`: interactive decision dashboard
- `data/build_artifacts.py`: single source for all reported metrics and markdown

## Run locally

```bash
python -m venv .venv
# Windows PowerShell: .venv\\Scripts\\Activate.ps1
pip install -r requirements.txt
python data/generate_data.py
python data/build_artifacts.py
streamlit run app/streamlit_app.py
```

The generator writes both CSV and Parquet. Re-running `build_artifacts.py` refreshes every number in the docs, notebooks, derived extracts, and this README from the current data.
"""
    (ROOT / "README.md").write_text(readme, encoding="utf-8")
    print(json.dumps(summary, indent=2, default=float))


if __name__ == "__main__":
    main()
